### ISSUE TITLE
BadMessageException: 400: Bad Request

### ISSUE THREAD

**Issue by jkwiecien** [Kotlin/ktor#79] opened 2017-03-27 19:30 UTC
Please provide some simple sample project that isn't dependant from the whole repository. For a rookie Getting started isn't enough to start Hello Word. I'm getting this when trying to access http://localhost:8080/ and don't know why

>  DEBUG org.eclipse.jetty.http.HttpParser - Parse exception: HttpParser{s=END,0 of 0} for HttpChannelOverHttp@37cc43a2{r=1,c=false,a=IDLE,uri=//localhost:8080/}
> org.eclipse.jetty.http.BadMessageException: 400: Bad Request
> 	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1464)
> 	at org.eclipse.jetty.server.HttpConnection.parseRequestBuffer(HttpConnection.java:350)
> 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:234)
> 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
> 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
> 	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
> 	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:122)
> 	at org.eclipse.jetty.util.thread.strategy.ExecutingExecutionStrategy.invoke(ExecutingExecutionStrategy.java:58)
> 	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:201)
> 	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:133)
> 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
> 	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
> 	at java.lang.Thread.run(Thread.java:745)
> Caused by: java.lang.AbstractMethodError: Method org/eclipse/jetty/server/HttpChannelOverHttp.contentComplete()Z is abstract
> 	at org.eclipse.jetty.server.HttpChannelOverHttp.contentComplete(HttpChannelOverHttp.java)
> 	at org.eclipse.jetty.http.HttpParser.handleHeaderContentMessage(HttpParser.java:597)
> 	at org.eclipse.jetty.http.HttpParser.parseFields(HttpParser.java:1115)
> 	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1369)
> 	... 12 common frames omitted

**Comment by jkwiecien** [comment] 2017-03-27 19:50
Yeah but samples use 
```
fun Application.main() {
    install(DefaultHeaders)
    install(CallLogging)
    install(Routing) {
        get("/") {
            call.respondText("Hello, World!")
        }
    }
}
```

not the `embeddedNetty` . But I don't think that's the issue. I ran it both ways always getting the same 400. I got the feeling there are many connections between pom files, while I'm trying to create single module project from scratch

**Comment by cy6erGn0m** [comment] 2017-03-31 18:25
> Caused by: java.lang.AbstractMethodError: Method org/eclipse/jetty/server/HttpChannelOverHttp.contentComplete()Z is abstract

you definitely have something wrong with your classpath: bad versions comes from somewhere

**Comment by orangy** [comment] 2017-04-24 10:23
Did you resolve the issue with classpath?

**Comment by orangy** [comment] 2017-06-05 15:58
Closing for now, please provide more info if the problem is still valid.

**Closed by orangy** 2017-06-05 15:58 UTC
Labels: help
